import Contact from "@/components/Contact";
import TransitionEffect from "@/components/TransitionEffect";
import Head from "next/head";
import React from "react";

const contact = () => {
  return (
    <>
      <Head>
        <title> Emmanuel | Contact Me </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Contact />
    </>
  );
};

export default contact;
